name: pomodoro
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  get: ^4.6.3
  uuid: ^3.0.6
  intl: ^0.17.0
  lottie: ^1.3.0
  sqflite: ^2.0.2+1
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  responsive_sizer: ^3.0.8
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  circular_countdown_timer: ^0.2.1
  mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/app/assets/images/
    - lib/app/assets/svgs/
    - lib/app/assets/json/
